=== JoeyEamigh/snapcast-multiroom/config.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/JoeyEamigh/snapcast-multiroom/main/product.schema.json",
  "title": "snapcast-multiroom config",
  "description": "config for snapcast-multiroom",
  "type": "object",
  "properties": {
    "serverAddress": {
      "description": "the address of the snapcast server in the form IP:PORT",
      "type": "string"
    },
    "devices": {
      "description": "the snapcast devices to be controlled by snapcast-multiroom",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "the snapcast id of the device",
            "type": "string"
          },
          "preferredName": {
            "description": "the preferred name for the device (will be set by snapcast-multiroom)",
            "type": "string"
          }
        },
        "required": ["id"]
      }
    },
    "groups": {
      "description": "the snapcast devices to be controlled by snapcast-multiroom",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "the name of the group",
            "type": "string"
          },
          "devices": {
            "description": "which devices are in the group",
            "type": "array",
            "items": {
              "id": "string"
            }
          }
        },
        "required": ["devices"]
      }
    },
    "zones": {
      "description": "the zones to be controlled by snapcast-multiroom",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "the id of the stream - generally the name set in the stream uri",
            "type": "string"
          },
          "stream": {
            "description": "the stream to be created for the zone e.g. librespot:///usr/bin/librespot?name=<stream_name>&devicename=<zone_name>&bitrate=320&volume=100&normalize=false&autoplay=true",
            "type": "string"
          },
          "groups": {
            "description": "the groups in the zone",
            "type": "array",
            "items": {
              "id": "string"
            }
          }
        },
        "required": ["id", "stream", "groups"]
      }
    }
  },
  "required": ["serverAddress", "devices", "groups", "zones"]
}

=== JoeyEamigh/snapcast-multiroom/config.example.json
{
  "$schema": "https://raw.githubusercontent.com/JoeyEamigh/snapcast-multiroom/main/config.schema.json",
  "serverAddress": "127.0.0.1:1705",
  "devices": [
    {
      "id": "device-1",
      "preferredName": "Device One"
    },
    {
      "id": "device-1-subwoofer",
      "preferredName": "Device One Subwoofer"
    },
    {
      "id": "device-2",
      "preferredName": "Device Two"
    }
  ],
  "groups": [
    {
      "name": "group-1",
      "devices": ["device-1", "device-1-subwoofer"]
    },
    {
      "name": "group-2",
      "devices": ["device-2"]
    }
  ],
  "zones": [
    {
      "id": "Group-One-Spotify",
      "stream": "librespot:///usr/bin/librespot?name=Group-One-Spotify&devicename=Group One&bitrate=320&autoplay=true&volume=50&params=--device-type%20speaker",
      "groups": ["group-1"]
    },
    {
      "id": "Group-Two-Spotify",
      "stream": "librespot:///usr/bin/librespot?name=Group-Two-Spotify&devicename=Group Two&bitrate=320&autoplay=true&volume=50&params=--device-type%20speaker",
      "groups": ["group-2"]
    },
    {
      "id": "Both-Groups-Spotify",
      "stream": "librespot:///usr/bin/librespot?name=Both-Groups-Spotify&devicename=Both Groups&bitrate=320&autoplay=true&volume=50&params=--device-type%20speaker",
      "groups": ["group-1", "group-2"]
    }
  ]
}
